[package]
name = "mod-hotkey-registry"
edition = "2021"
version.workspace = true

[lib]
crate-type = ["cdylib"]
name = "hotkey_registry"

[dependencies]
log = { workspace = true }
win_dbg_logger = { workspace = true }

[dependencies.windows]
version = "0.48"
features = [
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
]
